version: "3.8"

services:
  bot:
    build: .
    image: molodec-bot
    container_name: molodec-bot
    volumes:
      - ./base:/app/base
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped